name: .NET Core

on: [push]
 #   branches: [ Branch2 ]
  #pull_request:
   # branches: [ Branch2 ] 

jobs: 
   
   build:

    runs-on: self-hosted

    steps:
      - name: Generate certificates for next step
        uses: kofemann/action-create-certificate@v0.0.4

        with:
          hostcert: 'hostcert.pem'
          hostkey:  'hostkey.pem'
          cachain:  'ca-chain.pem'

      - name: Use generated certificates
        run: |
            openssl x509 -in hostcert.pem -noout -text
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: 2.1
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Publish
        run: dotnet publish --configuration Release --no-restore --output C:/SampleRepoPublish
